language: ruby
sudo: false

services:
  - postgresql

addons:
  postgresql: "9.4"

env:
- DATABASE_URL=postgres://localhost/anrop-aar

cache:
  - bundler

rvm:
  - 2.6.5

before_script:
  - bundle exec rails db:setup

script:
  - bundle exec rails test
